name: project
description: "Secret Santa project"
publish_to: 'none' #


version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter


  flutter_riverpod: ^2.0.0
  file_picker: ^5.3.0
  csv: ^5.0.1
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true
  assets:
   - assets/snowflake_bg.png

